### PR TITLE
improve dotimes

### PR DESCRIPTION
**Pull request by kariya-mitsuru**
1. A loop body can consist of zero or two or more form(s).

```
   Ex. (dotimes (i 10))                            ; zero
       (dotimes (i 10) (print i) (print (* i i)))  ; two
```
1. A result form can be specified.  
   A loop variable has a one past the end value (i.e. specified value) when the result form is evaluated.  
   If it is not specified, the result of `dotimes` is nil.

```
   Ex. (dotimes (i 10 i))        ; -> 10
       (dotimes (i 10 (* i i)))  ; -> 100
       (dotimes (i 10))          ; -> nil
```

### CODE REVIEW

**Comment by mattn** [comment]
Oh, I didn't know. Thanks

**Comment by mattn** [comment]
BTW, do you know the website or internet resource which have whole of spec of common lisp?

**Comment by kariya-mitsuru** [comment]
I often refer the [Common Lisp HyperSpec](http://www.lispworks.com/documentation/HyperSpec/Front/index.htm).
It is comprehensive but hyper huge and hyper esoteric. (my personal impressions)

**Comment by mattn** [comment]
thank you

**Comment by mattn** [comment]
https://www.cs.cmu.edu/Groups/AI/util/html/cltl/clm/index.html

This is an index that is all?

**Comment by kariya-mitsuru** [comment]
> https://www.cs.cmu.edu/Groups/AI/util/html/cltl/clm/index.html
> 
> This is an index that is all?

[CLHS](http://www.lispworks.com/documentation/HyperSpec/Front/index.htm) has a full [Symbol Index](http://www.lispworks.com/documentation/HyperSpec/Front/X_AllSym.htm) too.

I think the common lisp is too huge to understand, for human. (my personal impressions)
LIPS is the language of the gods.  (my personal impressions)

**Comment by mattn** [comment]
thanks again

**Pull request merged**
